### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by tomatobybike** [jonschlinkert/gray-matter#143]
when i use gray-matter in vite react project, found this error:

```
react_devtools_backend.js:3973 ReferenceError: Buffer is not defined
    at Object.exports2.toBuffer (utils.js:36:38)
    at module2.exports (to-file.js:28:36)
    at matter (index.js:34:14)
    at getFile (Docs.jsx:154:17)
```

how to fix

**Comment by tomatobybike** [comment]
Install this library

```sh
yarn add @esbuild-plugins/node-globals-polyfill
```

and add this in your vite.config.js

```js

import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
export default defineConfig({
    // ...other config settings
    optimizeDeps: {
        esbuildOptions: {
            // Node.js global to browser globalThis
            define: {
                global: 'globalThis'
            },
            // Enable esbuild polyfill plugins
            plugins: [
                NodeGlobalsPolyfillPlugin({
                    buffer: true
                })
            ]
        }
    }
}
add this import to your vite.config.js


```

**Comment by TeemuKoivisto** [comment]
Wow rarely I find solutions that work straight away, thanks @tomatobybike !

**Comment by segevfiner** [comment]
Would be nicer if this library was compatible with the browser to begin with, or add a browser build defined in the `package.json`

**Comment by segevfiner** [comment]
It seems optimizeDeps isn't run on `vite build`...

**Comment by andrewspy** [comment]
vite-plugin-node-polyfills should solve both dev/build problem.
See: https://www.npmjs.com/package/vite-plugin-node-polyfills

**Comment by transtone** [comment]
if use nuxtjs, see https://github.com/nuxt/nuxt/issues/25016

**Comment by shubham4538** [comment]
> Install this library
> 
> ```shell
> yarn add @esbuild-plugins/node-globals-polyfill
> ```
> 
> add this import to your vite.config.js
> 
> and add this in your vite.config.js
> 
> ```js
> import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
> export default defineConfig({
>     // ...other config settings
>     optimizeDeps: {
>         esbuildOptions: {
>             // Node.js global to browser globalThis
>             define: {
>                 global: 'globalThis'
>             },
>             // Enable esbuild polyfill plugins
>             plugins: [
>                 NodeGlobalsPolyfillPlugin({
>                     buffer: true
>                 })
>             ]
>         }
>     }
> }
> ```
Yes this works but when I checked the matter, it has `content` as html data with also includes the metadeta which I included in the `--- ... ---` and the data field was an empty object.

**Comment by s-light** [comment]
> vite-plugin-node-polyfills should solve both dev/build problem. See: https://www.npmjs.com/package/vite-plugin-node-polyfills

did work for me in a quasar vue.js vite setup.

`quasar.conf.js`
```js
const { configure } = require("quasar/wrappers");

// required for the gray-matter plugin.
// https://github.com/davidmyersdev/vite-plugin-node-polyfills
const { nodePolyfills } = require("vite-plugin-node-polyfills");

module.exports = configure(function (/* ctx */) {
    return {
      build: {
      vitePlugins: [
                      nodePolyfills(),
            ],
        },
    };
});
```

**Comment by winner106** [comment]
in tauri+react project, this should work:

> import { nodePolyfills } from "vite-plugin-node-polyfills";
> plugins: [react(), tsconfigPaths(), nodePolyfills()],

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
import { nodePolyfills } from "vite-plugin-node-polyfills";

const host = process.env.TAURI_DEV_HOST;

// https://vitejs.dev/config/
export default defineConfig(async () => ({
  plugins: [react(), tsconfigPaths(), nodePolyfills()],

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
```

**Comment by nyrzeff** [comment]
None of the above worked for me. What worked though was installing https://www.npmjs.com/package/vite-plugin-node-polyfills. I also had to remove the `node-globals-polyfill` plugin or the dev environment would break.

EDIT: Someone had already mentioned this plugin but for some reason I didn't notice lol. I'll still leave this here in case someone has the same problem, for clarity's sake.

**Comment by naranyala** [comment]
the author already solves the problem for me, the issue can be close

**Comment by RyanGarber** [comment]
Using polyfills is not a solution — it's finicky at best if you have any real dependencies. It would not be difficult to fix this in any number of ways:

* add exports that do not use Buffer
* use anything other than Node's built-in Buffer class in general
* or just make the call conditional to Buffer being defined...

If I have the time to do this I will make a PR... but the activity on this repo doesn't exactly scream confidence for it being accepted...

Edit: I found two alternatives with proper ESM exports and browser support:
1. https://github.com/ryoppippi/gray-matter-es — direct fork, a few stars, last commit 4 months ago
2. https://github.com/jxson/front-matter — different library, 600+ stars, last commit 6 years ago

**Comment by mrdude8391** [comment]
> vite-plugin-node-polyfills should solve both dev/build problem. See: https://www.npmjs.com/package/vite-plugin-node-polyfills


Issue was solved for me after adding the plugin.  
```js
// vite.config.ts
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
  plugins: [
    nodePolyfills({ globals: { Buffer: true }}), 
  ],
});
```
